### PR TITLE
Fix #1406 and Add missing Russian (ru_ru) locale translations

### LINKED ISSUE #1406: Cable cannot be connected to Paylon with transformer
### Describe the bug

I don't know if this happens on Original HBM Nuclear Tech v1.7.10, but it happens on HBM Community Edition. This bug occurs when trying to connect a cable to the connector on the paylon with transformer, causing the cable to not connect and the electricity to not be connected, I have tried 2 ways but it doesn't work. I use `NTM-CE-1.12.2-2.1.1.0.jar`, I downloaded it on forge.

### Run URL

.

### Mod conflict check

Yes — reproduces with only NTM:CE

### Where does it happen?

Singleplayer (Forge)

### To Reproduce

1. Enter the world that was created
2. Taking in inventory (if Creative mode) or making paylon and cable
3. Place Paylon (Single/Triple) with Transformer
4. Place the cable connection from the socket or power generator to the Paylon with Transformer
5. Unable to connect cable with Paylon with Transformer connector

### Expected behavior

I hope this bug can be fixed because using paylon can tidy up the cable structure using a drum cable. This is one of those breaking bugs I hope gets fixed 🙂

### Screenshots, videos, crash report, logs

Image
Image

### Modlist

_No response_

### Additional context

- OS: Android 13 (Mojo Launcher Minecraft Java)
- Java: (I don't know it just says `default` there)
- Forge/Cleanroom: Forge
- Server software (if any):
- Notes:

### PR DESCRIPTION
**Pull request by Nullstyx**
Fix #1406 and Add missing Russian (ru_ru) locale translations

### CODE REVIEW

**Comment by TheSlize** [comment]
Bruh LMAO

I've just fixed #1406...

File: src/main/java/com/hbm/lib/Library.java [hunk 1]
```diff
@@ -926,7 +927,31 @@ public static boolean canConnect(IBlockAccess world, BlockPos pos, ForgeDirectio
         if (te instanceof IEnergyConnectorMK2) {
             IEnergyConnectorMK2 con = (IEnergyConnectorMK2) te;
 
-            if (con.canConnect(dir.getOpposite() /* machine's connecting side */)) return true;
+            if (con.canConnect(dir.getOpposite())) return true;
+        }
```
Comment (TheSlize) [inline src/main/java/com/hbm/lib/Library.java]: the solution lies in canConnectTo, not here
